[package]
name = "aljabar"
version = "0.2.1"
authors = ["Matthew Plant <map@maplant.com>"]
edition = "2018"
description = "A super generic, super experimental linear algebra library."
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
